# MANAGED BY PUPPET

source ~/.kiosk_config

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

if [ -z $DISPLAY ] && [ $(tty) = /dev/tty1 ] ; then
  while true ; do
    startx
  done
else
  export DISPLAY=:0.0
  alias x=xdotool
  alias xk='xdotool key'
  alias xt='xdotool type'
  alias xr='pgrep xinit | xargs kill'
fi

