#!/usr/bin/sh

xset -dpms
xset s off
xset s noblank

unclutter --fork --start-hidden
xdotool mousemove 0 0

chromium "--window-size=$WINDOW_WIDTH,$WINDOW_HEIGHT" --remote-debugging-port=8080 --kiosk "$KIOSK_URL_A"

