#!/usr/bin/sh

source ~/.kiosk_config

xset -dpms
xset s off
xset s noblank

unclutter --fork --start-hidden
xdotool mousemove 0 0
xbindkeys

chromium "--window-size=$WINDOW_WIDTH,$WINDOW_HEIGHT" --remote-debugging-port=8080 --kiosk "$KIOSK_URL_A"

