#!/usr/bin/sh

source ~/.kiosk_config

xset -dpms
xset s off
xset s noblank

unclutter --fork --start-hidden
xdotool mousemove 0 0
xbindkeys

chromium "--window-size=$WINDOW_WIDTH,$WINDOW_HEIGHT" "--remote-debugging-port=$DEBUG_PORT" "--proxy-server=$proxy_server" "--proxy-bypass-list=$proxy_bypass_list" --kiosk "$KIOSK_URL_A"

